url: https://popong.com
baseurl: ""

# Site settings
title: Team POPONG
email: contact@popong.com

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: A
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: B
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: C
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Partners
partners:
- image: partner-cckorea.png
  url: http://cckorea.org/
- image: partner-okfkorea.png
  url: http://okfn.kr/
- image: partner-sunlight.png
  url: http://sunlightfoundation.com/
- image: partner-openparl.png
  url: http://openingparliament.org/

# Social networks usernames
# (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/teampopong
  - title: facebook
    url: http://facebook.com/teampopong
  - title: github
    url: http://github.com/teampopong

# Build settings
markdown: kramdown
permalink: pretty
